server:
  port: 8082
  
spring:
  datasource:
    username: root
    password: baba
    url: jdbc:mysql://localhost:3306/projectdb
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
     
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    
destination: C:\\Users\\BabaFakruddinDharuba\\Desktop\\Project\\Templates\\flattenPdf\\
