
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:
   cloud:
    gateway:
      routes:
      - id: flattenApiService
        uri: lb://FLATTENPDF-API-SERVICE
        predicates:
        - Path=/flattenpdf-api/**
